# Generated by Django 4.1.6 on 2023-02-12 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ash', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='about',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='category',
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
